apiVersion: v1
kind: Service
metadata:
  name: svc-nodejs
  namespace: nodejs
spec:
  type: NodePort
  selector:
      app: fibo-nodejs
  ports:
    - targetPort: 9090
      port: 80
      nodePort: 31890